Repository fedemelo/Team-15-Swifties, pull requests merged in 2024-10, with the labels that each got.

#13 Feat/publish product form #6
  .gitignore
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcuserdata/fedemelo.xcuserdatad/IDEFindNavigatorScopes.plist
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcuserdata/fedemelo.xcuserdatad/UserInterfaceState.xcuserstate
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade/ImagePicker.swift
  UniTrade/UniTrade/Info.plist
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: enhancement

#10 Feat/home view #9
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/santiagomartinez.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcuserdata/santiagomartinez.xcuserdatad/UserInterfaceState.xcuserstate
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/xcuserdata/santiagomartinez.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade/Category.swift
  UniTrade/UniTrade/CategoryItemView.swift
  UniTrade/UniTrade/CategoryScroll.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/SearchandFilterBar.swift
  UniTrade/UniTrade/SortButton.swift
Labels: enhancement

#14 Feat/login and auth view
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade.xcodeproj/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UniTrade/UniTrade/Assets.xcassets/AccentColor.colorset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/AppIcon.appiconset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/AppIcon.appiconset/UniTrade logo.png
  UniTrade/UniTrade/Assets.xcassets/Logo Dark Mode.imageset/1.png
  UniTrade/UniTrade/Assets.xcassets/Logo Dark Mode.imageset/4.png
  UniTrade/UniTrade/Assets.xcassets/Logo Dark Mode.imageset/6.png
  UniTrade/UniTrade/Assets.xcassets/Logo Dark Mode.imageset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/Logo Light Mode.imageset/2.png
  UniTrade/UniTrade/Assets.xcassets/Logo Light Mode.imageset/3.png
  UniTrade/UniTrade/Assets.xcassets/Logo Light Mode.imageset/5.png
  UniTrade/UniTrade/Assets.xcassets/Logo Light Mode.imageset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/Logo Microsoft.imageset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/Logo Microsoft.imageset/logo microsoft 1.png
  UniTrade/UniTrade/Assets.xcassets/Logo Microsoft.imageset/logo microsoft 2.png
  UniTrade/UniTrade/Assets.xcassets/Logo Microsoft.imageset/logo microsoft.png
  UniTrade/UniTrade/FirebaseAuthManager.swift
  UniTrade/UniTrade/FirebaseManager.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/GoogleService-info 2.plist
  UniTrade/UniTrade/Info.plist
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/LoginViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/TemplateView.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/Untitled.swift
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/User.swift
Labels: auth

#16 Feat/select preferred categories#15
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LoginViewModel.swift
Labels: user preferences, smart feature

#22 Feat/add navigation to home
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/MainView.swift
Labels: enhancement

#23 Add dark mode to views that lacked it
  UniTrade/DesignSystem/Sources/DesignSystem/Color.swift
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/CategoryItemView.swift
  UniTrade/UniTrade/ContentView.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/Item.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/SearchandFilterBar.swift
  UniTrade/UniTrade/SortButton.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadImageButton.swift
Labels: enhancement

#24 Improve category selection layout for FirstTimeUserView
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade/CategoryName.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LoginViewModel.swift
Labels: user preferences, smart feature

#28 Bug/uniformize behaviour when horizontal
  UniTrade/DesignSystem/Sources/DesignSystem/Color.swift
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcuserdata/santiagomartinez.xcuserdatad/UserInterfaceState.xcuserstate
  UniTrade/UniTrade/CategoryItemView.swift
  UniTrade/UniTrade/CategoryName.swift
  UniTrade/UniTrade/CategoryScroll.swift
  UniTrade/UniTrade/ContentView.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/Filter.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/FontTransformerUI.swift
  UniTrade/UniTrade/Item.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/LoginViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/NumericTextField.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/Product.swift
  UniTrade/UniTrade/SearchandFilterBar.swift
  UniTrade/UniTrade/SortButton.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/UploadProductView.swift
Labels: bug

#30 Bug/uniformize behaviour when horizontal
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadProductView.swift
Labels: bug

#32 Update .gitignore
  .gitignore
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcuserdata/santiagomartinez.xcuserdatad/UserInterfaceState.xcuserstate
  UniTrade/UniTrade.xcodeproj/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/xcuserdata/santiagomartinez.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UniTrade/UniTrade.xcodeproj/xcuserdata/santiagomartinez.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: bug

#33 Feat/dynamic cas light and dark mode
  UniTrade/UniTrade/UniTradeApp.swift
Labels: enhancement

#35 Feat/unify swift flutter UI
  UniTrade/DesignSystem/Sources/DesignSystem/Font.swift
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/APIConfig.swift
  UniTrade/UniTrade/ButtonWithIcon.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: enhancement

#34 Feat/connect homeview with firebase #20
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/NumericTextField.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/Product.swift
  UniTrade/UniTrade/ProductCategoryGroupManager.swift
Labels: enhancement

#36 Allow user to choose account on sign-in and fix navigation issue with FirstTimeUserView #15
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LoginViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/UniTradeApp.swift
Labels: auth, user preferences

#37 Beautify price formatting
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/CurrencyFormatter.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/UploadProductStrategies.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: enhancement

#39 feat: Implement Decorator Design Pattern and CrashLogger integration
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/BasePrice.swift
  UniTrade/UniTrade/CategoryItemView.swift
  UniTrade/UniTrade/CrashLogger.swift
  UniTrade/UniTrade/CurrencyDecorator.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/FormatDecorator.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/ListingItemViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/Price.swift
  UniTrade/UniTrade/PriceDecorator.swift
  UniTrade/UniTrade/ProductCategoryGroupManager.swift
Labels: bug, enhancement

#38 Change API URL
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/APIConfig.swift
Labels: enhancement

#40 Feat/select preferred categories#15
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/cabecitas 1.png
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/cabecitas 2.png
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/cabecitas.png
  UniTrade/UniTrade/CategoryScroll.swift
  UniTrade/UniTrade/Info.plist
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/SplashScreenView.swift
  UniTrade/UniTrade/UniTradeApp.swift
Labels: enhancement, auth

#43 Change test to production API
  UniTrade/UniTrade/APIConfig.swift
Labels: enhancement

#44 Develop
  .gitignore
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/DesignSystem/Sources/DesignSystem/Color.swift
  UniTrade/DesignSystem/Sources/DesignSystem/Font.swift
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcuserdata/santiagomartinez.xcuserdatad/UserInterfaceState.xcuserstate
  UniTrade/UniTrade.xcodeproj/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UniTrade/UniTrade.xcodeproj/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/xcuserdata/santiagomartinez.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  UniTrade/UniTrade.xcodeproj/xcuserdata/santiagomartinez.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade/APIConfig.swift
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/Contents.json
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/cabecitas 1.png
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/cabecitas 2.png
  UniTrade/UniTrade/Assets.xcassets/Image Auth.imageset/cabecitas.png
  UniTrade/UniTrade/BasePrice.swift
  UniTrade/UniTrade/ButtonWithIcon.swift
  UniTrade/UniTrade/CategoryItemView.swift
  UniTrade/UniTrade/CategoryName.swift
  UniTrade/UniTrade/CategoryScroll.swift
  UniTrade/UniTrade/ContentView.swift
  UniTrade/UniTrade/CrashLogger.swift
  UniTrade/UniTrade/CurrencyDecorator.swift
  UniTrade/UniTrade/CurrencyFormatter.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/Filter.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/FontTransformerUI.swift
  UniTrade/UniTrade/FormatDecorator.swift
  UniTrade/UniTrade/Info.plist
  UniTrade/UniTrade/Item.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/ListingItemViewModel.swift
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/LoginViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/NumericTextField.swift
  UniTrade/UniTrade/Price.swift
  UniTrade/UniTrade/PriceDecorator.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/Product.swift
  UniTrade/UniTrade/ProductCategoryGroupManager.swift
  UniTrade/UniTrade/SearchandFilterBar.swift
  UniTrade/UniTrade/SortButton.swift
  UniTrade/UniTrade/SplashScreenView.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/UploadProductStrategies.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: enhancement

#45 Feat/profile view and dark light preference
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/LightDarkModeSettingsView.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/ModeSettings.swift
  UniTrade/UniTrade/MyListingsView.swift
  UniTrade/UniTrade/MyOrdersView.swift
  UniTrade/UniTrade/ProfileView.swift
  UniTrade/UniTrade/ProfileViewModel.swift
  UniTrade/UniTrade/TemplateView.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/UploadProductView.swift
Labels: enhancement

#56 PR: Feat/multithreading for products in splash #47
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/UniTradeApp.swift
Labels: enhancement

#57 Add offline warning banner for login #53
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/LoginViewModel.swift
Labels: auth, eventual connectivity
