Repository fedemelo/Team-15-Swifties, pull requests merged in 2024-11, with the labels that each got.

#59 fix: Fix bug related to the navigation to preferences page
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade/MainView.swift
Labels: bug, user preferences

#60 Feat/add warning messages when offline#53
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/LoginViewModel.swift
Labels: auth, eventual connectivity

#63 Feat/cache product upload
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/NetworkMonitor.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: bug, enhancement

#64 Feat/view mylistings #50v2
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/MyListingsView.swift
  UniTrade/UniTrade/MyListingsViewModel.swift
  UniTrade/UniTrade/UserProduct.swift
  UniTrade/UniTrade/UserProductItemView.swift
  UniTrade/UniTrade/UserProductViewModel.swift
Labels: enhancement

#67 Add response time measure for new listings #66
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: analytics

#68 Save user theme preference to Firestore based on mode selection
  UniTrade/UniTrade/ModeSettings.swift
Labels: analytics

#69 feat/create a view where users can choose their major and semester#55
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/LoginViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/MajorName.swift
  UniTrade/UniTrade/ProfileViewModel.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/User.swift
Labels: auth, smart feature, eventual connectivity

#70 Eventual Connectivity implemented for Products of user and general view
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/ErrorView.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/ListingItemViewModel.swift
  UniTrade/UniTrade/MyListingsView.swift
  UniTrade/UniTrade/Product.swift
Labels: enhancement, eventual connectivity

#71 Feat/keep track of time in every screen
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/Mariana1.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade/CategoryScroll.swift
  UniTrade/UniTrade/ChooseUploadTypeView.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LightDarkModeSettingsView.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/MyListingsView.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/ProfileView.swift
  UniTrade/UniTrade/ProfileViewModel.swift
  UniTrade/UniTrade/ScreenTimeViewModel.swift
  UniTrade/UniTrade/SplashScreenView.swift
  UniTrade/UniTrade/UploadProductView.swift
Labels: analytics

#73 BQs implemented
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/santiagomartinez.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/ListingItemViewModel.swift
  UniTrade/UniTrade/Product.swift
  UniTrade/UniTrade/UploadProductView.swift
Labels: enhancement, analytics

#74 Sprint 3
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/santiagomartinez.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UniTrade/UniTrade/CategoryScroll.swift
  UniTrade/UniTrade/ChooseUploadTypeView.swift
  UniTrade/UniTrade/ErrorView.swift
  UniTrade/UniTrade/ExplorerView.swift
  UniTrade/UniTrade/ExplorerViewModel.swift
  UniTrade/UniTrade/FilterView.swift
  UniTrade/UniTrade/FirstTimeUserView.swift
  UniTrade/UniTrade/LightDarkModeSettingsView.swift
  UniTrade/UniTrade/ListingItemView.swift
  UniTrade/UniTrade/ListingItemViewModel.swift
  UniTrade/UniTrade/LoginView.swift
  UniTrade/UniTrade/LoginViewModel.swift
  UniTrade/UniTrade/MainView.swift
  UniTrade/UniTrade/MajorName.swift
  UniTrade/UniTrade/ModeSettings.swift
  UniTrade/UniTrade/MyListingsView.swift
  UniTrade/UniTrade/MyListingsViewModel.swift
  UniTrade/UniTrade/MyOrdersView.swift
  UniTrade/UniTrade/NetworkMonitor.swift
  UniTrade/UniTrade/PriceRangeView.swift
  UniTrade/UniTrade/Product.swift
  UniTrade/UniTrade/ProfileView.swift
  UniTrade/UniTrade/ProfileViewModel.swift
  UniTrade/UniTrade/ScreenTimeViewModel.swift
  UniTrade/UniTrade/SplashScreenView.swift
  UniTrade/UniTrade/TemplateView.swift
  UniTrade/UniTrade/UniTradeApp.swift
  UniTrade/UniTrade/UploadImageButton.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
  UniTrade/UniTrade/User.swift
  UniTrade/UniTrade/UserProduct.swift
  UniTrade/UniTrade/UserProductItemView.swift
  UniTrade/UniTrade/UserProductViewModel.swift
Labels: enhancement, auth, eventual connectivity, analytics

#75 Add exhaustive validations for fields in upload product view
  UniTrade/DesignSystem/.swiftpm/xcode/xcuserdata/fedemelo.xcuserdatad/xcschemes/xcschememanagement.plist
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/ButtonWithIcon.swift
  UniTrade/UniTrade/FormFieldView.swift
  UniTrade/UniTrade/FormFieldsSection.swift
  UniTrade/UniTrade/UploadButtonSection.swift
  UniTrade/UniTrade/UploadProductHeaderView.swift
  UniTrade/UniTrade/UploadProductStrategies.swift
  UniTrade/UniTrade/UploadProductView.swift
  UniTrade/UniTrade/UploadProductViewModel.swift
Labels: bug

#77 Fix bug counting favorites on search
  UniTrade/UniTrade/ExplorerViewModel.swift
Labels: bug

#78 Unify Preferences Page UI with Flutter Version
  UniTrade/UniTrade.xcodeproj/project.pbxproj
  UniTrade/UniTrade/FirstTimeUserView.swift
Labels: enhancement

#79 Update navbar to match with flutter implementation
  UniTrade/UniTrade/MainView.swift
Labels: enhancement
